app:
    url: http://localhost:8080
cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS}
            secretKey: ${AWS_SECRET}
        end-point:
            uri: https://sqs.us-east-2.amazonaws.com/608820787390/RZIN-queue
        region:
            auto: false
            static: us-east-2
    s3:
        endpoint:
            bucketname: avatarimage-s3bucket
            url: https://s3.us-east-2.amazonaws.com/
logging:
    level:
        com:
            amazonaws:
                internal:
                    InstanceMetadataServiceResourceFetcher: error
                util:
                    EC2MetadataUtils: error
        liquibase: INFO
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: DEBUG
                        StatementCreatorUtils: TRACE
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ${DB_PASS}
        url: jdbc:postgresql://localhost:5432/postgressbaza?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        username: ${DB_LOGIN}
    data:
        rest:
            default-page-size: 10
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
    mail:
        host: smtp.gmail.com
        password: ${MAIL_PASS}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
        username: ${MAIL_LOGIN}
    servlet:
        multipart:
            enabled: true
            location: ${java.io.tmpdir}
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc
