--liquibase formatted postgresql
--changeset jsikora:1
CREATE TABLE user_entity (
                             id SERIAL,
                             username varchar(255),
                             password varchar(255),
                             email varchar(255),
                             firstname varchar(255),
                             lastname varchar(255),
                             age smallint
);

--changeset jsikora:2
ALTER TABLE user_entity ADD phone VARCHAR(255) NULL;

--changeset jsikora:3
ALTER TABLE user_entity ALTER COLUMN id TYPE BIGINT;

--changeset jsikora:4
ALTER TABLE user_entity ADD uuid VARCHAR(255) NOT NULL;

--changeset jsikora:5
ALTER TABLE user_entity ADD is_active BOOLEAN;

-- big change
--changeset jsikora:6
ALTER TABLE user_entity ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE user_entity ALTER COLUMN id SET NOT NULL;
ALTER TABLE user_entity ADD CONSTRAINT pk_user_entity PRIMARY KEY (id);

--changeset jsikora:7
ALTER TABLE user_entity ADD activation_link VARCHAR(64);

--changeset jsikora:8
ALTER TABLE user_entity ADD avatar_link VARCHAR(255);

--changeset jsikora:9
ALTER TABLE user_entity ADD is_enabled BOOLEAN;
